### ISSUE TITLE
Layer Visibility Navigation

### ISSUE THREAD

**Issue by tle7pa** [uva-cfrm/VDOT_P4P#21]
Consider making the icon stating the layer is not visible at current map scale a button to change the map scale to the nearest one at which the layer is visible

**Comment by cap8c** [comment]
There's a similar request about only showing certain features at different zoom levels, so maybe we can combine those topics.  The idea is that when I zoom to a view where I see all of Virginia, I can only see interstates but not local roads.  So this suggestions would show an icon next to different road types/legend that zooms to the right scale.  Agree it's not intuitive right now.

**Comment by cap8c** [comment]
Per Yogesh, this will be built into new versions where all layers are visible at all scales
